### PR TITLE
Fixed PBC fixing when unsquashing for dummy atoms

### PR DESCRIPTION
**Pull request by msuruzhon**
This fixes a small bug related to the dummy atom not being properly translated after fixing the PBC coordinates of AMBER output.

### CODE REVIEW

**Review by xiki-tempula — APPROVED** [review]
LGTM

**Comment by msuruzhon** [comment]
@lohedges Our macOS CI is failing at a test checking the box angles, but these pass for Linux, even though they should be using the same Sire versions. Do you have any idea why that might be happening? Many thanks.

**Comment by lohedges** [comment]
Hi @msuruzhon. Yes, I understand what's going on. The Linux package is build number 1, which contains the updated triclinic box fix. This was only asked for on Linux, so isn't applied to 2023.2.3 on macOS, which is still build zero. The second fix changed the preferential direction of rounding to get things to work with OpenMM, so some of the values returned by `BioSimSpace.Box` are different. (These now agree with the expected reduced box vectors for GROMACS.) The angles used in the tests were updated [here](https://github.com/OpenBioSim/biosimspace/commit/26e7cfd9b182998fe1885b4adc0d4fa6095be33d).

If you need this on macOS too, then I could try to build a version locally and upload. (Or ask Christopher to do it.) Alternatively, you could just add a platform check and swap the ordering of the expected angles on macOS.

**Comment by msuruzhon** [comment]
@lohedges Thanks, this makes sense. I think we don't need a macOS build for that right now, I will just `xfail` it then.

**Pull request merged**
