### PR TITLE
Merge some recent bugfixes

### PR DESCRIPTION
**Pull request by msuruzhon**
This PR adds the recent bugfixes in the `prep-0.9.1` branch, as well as `fix_159` in the main repo.

### CODE REVIEW

**Comment by msuruzhon** [comment]
Hi @lohedges, our CI is failing because of some weird segfaults after the tests. Have you seen this before? Many thanks.

**Comment by lohedges** [comment]
No, I've not seen anything like that. I've had segfaults during tests (when there were bugs) but not after they've all completed. Do you see the same thing locally? If not, it might be worth seeing how much memory is consumed while they are running. Given they all passed, the teardown should be normal too.

**Comment by msuruzhon** [comment]
Thanks, I'll also try rerunning on `devel` to see if it's something introduced by this PR.

**Comment by msuruzhon** [comment]
So this isn't something we are only seeing for this branch, it suddenly started appearing in `devel` as well 1 week ago. The only dependency diff is the following, so maybe I should investigate that:

```
6c6
<  + argon2-cffi                          21.3.0  pyhd8ed1ab_0             conda-forge/noarch                  16kB
---
>  + argon2-cffi                          23.1.0  pyhd8ed1ab_0             conda-forge/noarch                  19kB
70d69
<  + flit-core                             3.9.0  pyhd8ed1ab_0             conda-forge/noarch                  49kB
149c148
<  + libarrow                             12.0.1  hb9dc469_9_cpu           conda-forge/linux-64                28MB
---
>  + libarrow                             13.0.0  hb9dc469_0_cpu           conda-forge/linux-64                28MB
205c204
<  + libzip                                1.9.2  hc929e4a_1               conda-forge/linux-64                99kB
---
>  + libzip                               1.10.1  h2629f0a_0               conda-forge/linux-64               108kB
292c291
<  + pyarrow                              12.0.1  py310hf9e7431_9_cpu      conda-forge/linux-64                 4MB
---
>  + pyarrow                              13.0.0  py310hf9e7431_0_cpu      conda-forge/linux-64                 4MB
295,296c294,295
<  + pydantic                              2.2.1  pyhd8ed1ab_0             conda-forge/noarch                 258kB
<  + pydantic-core                         2.6.1  py310hcb5633a_0          conda-forge/linux-64                 1MB
---
>  + pydantic                              2.3.0  pyhd8ed1ab_0             conda-forge/noarch                 258kB
>  + pydantic-core                         2.6.3  py310hcb5633a_0          conda-forge/linux-64                 1MB
```

**Comment by lohedges** [comment]
Okay. Let me know if you can't track it down and I can retrigger our `devel` build too. No doubt the offending dependency will be patched by the time you find it 😉

**Comment by msuruzhon** [comment]
Okay so it turned out to be `pyarrow`. On a different note, have you seen the ABFE error that is thrown in our macOS CI?

**Comment by lohedges** [comment]
Not sure. Will investigate tomorrow. Thanks for the heads up.

**Comment by lohedges** [comment]
It looks like that test has an incorrect `skipif` for GROMACS being missing, meaning that it isn't run on `macOS` for our CI. I'll fix now and see if I get the same error.

**Comment by lohedges** [comment]
It looks like this test passed previously in your CI and the code related to it hasn't been changed by this PR. Could you re-run to see if it is just something that is flaky? I see that it has a sleep command to wait for output to be generated, so perhaps this run was slower than expected.

**Comment by msuruzhon** [comment]
Hmm okay thanks, I'll rerun it

**Comment by msuruzhon** [comment]
@lohedges rerunning did seem to fix it! I guess I can merge then :)

**Pull request merged**
